# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGoia7rVR3R-MyuPpI8y3uH-O8iIT2AI
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from google.colab import files

(X_train,y_train),(X_test,y_test)=tf.keras.datasets.fashion_mnist.load_data()

print("Training Images :",X_train.shape)
print("Testing Images :",X_test.shape)

plt.figure(figsize=(10,5))

for i in range(10):

    plt.subplot(2,5,i+1)

    plt.imshow(X_train[i],cmap='gray')

    plt.title(y_train[i])

    plt.axis('off')

plt.show()

X_train=X_train/255.0
X_test=X_test/255.0

X_train=X_train.reshape(-1,28,28,1)
X_test=X_test.reshape(-1,28,28,1)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout

model=Sequential()

model.add(
    Conv2D(
        32,
        (3,3),
        activation='relu',
        input_shape=(28,28,1)
    )
)

model.add(MaxPooling2D())

model.add(
    Conv2D(
        64,
        (3,3),
        activation='relu'
    )
)

model.add(MaxPooling2D())

model.add(Flatten())

model.add(Dense(
    128,
    activation='relu'
))

model.add(Dropout(0.3))

model.add(Dense(
    10,
    activation='softmax'
))

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history=model.fit(
    X_train,
    y_train,
    epochs=3,
    validation_data=(X_test,y_test)
)

plt.plot(history.history['accuracy'])

plt.plot(history.history['val_accuracy'])

plt.title("CNN Accuracy")

plt.legend([
    "Training",
    "Validation"
])

plt.show()

uploaded=files.upload()

filename=list(uploaded.keys())[0]

img=cv2.imread(filename)

gray=cv2.cvtColor(
    img,
    cv2.COLOR_BGR2GRAY
)

face_detector=cv2.CascadeClassifier(
    cv2.data.haarcascades+
    'haarcascade_frontalface_default.xml'
)

faces=face_detector.detectMultiScale(
    gray,
    1.1,
    4
)

for(x,y,w,h) in faces:

    cv2.rectangle(
        img,
        (x,y),
        (x+w,y+h),
        (0,255,0),
        3
    )

plt.figure(figsize=(8,6))

plt.imshow(
    cv2.cvtColor(
        img,
        cv2.COLOR_BGR2RGB
    )
)

plt.title(
    f"Faces Found : {len(faces)}"
)

plt.axis('off')

plt.show()

uploaded=files.upload()

filename=list(uploaded.keys())[0]

img=cv2.imread(filename)

rgb=cv2.cvtColor(
    img,
    cv2.COLOR_BGR2RGB
)

plt.imshow(rgb)

plt.title("Original Image")

plt.axis('off')

plt.show()

gray=cv2.cvtColor(
    img,
    cv2.COLOR_BGR2GRAY
)

plt.imshow(
    gray,
    cmap='gray'
)

plt.title("Grayscale")

plt.axis('off')

plt.show()

blur=cv2.GaussianBlur(
    gray,
    (7,7),
    0
)

plt.imshow(
    blur,
    cmap='gray'
)

plt.title("Blurred Image")

plt.axis('off')

plt.show()

edges=cv2.Canny(
    gray,
    50,
    150
)

plt.imshow(
    edges,
    cmap='gray'
)

plt.title("Edge Detection")

plt.axis('off')

plt.show()

print("""
Assignment 3 Successfully Executed

1. CNN Fashion Recognition
2. Face Detection
3. Grayscale Conversion
4. Image Blur Processing
5. Edge Detection

All Computer Vision Tasks Completed
""")