# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hFfTFYoxAk1D7fpt69JQEnE7phOvNroY
"""

from google.colab import files

uploaded = files.upload()

!pip install seaborn

# Upload Dataset

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import r2_score, accuracy_score

# Load Dataset
data = pd.read_csv("Student_Data.csv")

# Features
X = data[['studytime','failures','absences']]
y = data['G3']

# ----------------------------
# Graph 1: Study Time vs Grade
# ----------------------------

plt.figure(figsize=(6,4))
plt.scatter(data['studytime'], data['G3'])
plt.title("Study Time vs Final Grade")
plt.xlabel("Study Time")
plt.ylabel("Final Grade")
plt.show()

# ----------------------------
# Graph 2: Absences vs Grade
# ----------------------------

plt.figure(figsize=(6,4))
plt.scatter(data['absences'], data['G3'])
plt.title("Absences vs Final Grade")
plt.xlabel("Absences")
plt.ylabel("Final Grade")
plt.show()

# ----------------------------
# Linear Regression
# ----------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

linear_pred = linear_model.predict(X_test)

print("LINEAR REGRESSION")
print("R2 Score:", round(r2_score(y_test, linear_pred), 2))

# ----------------------------
# Logistic Regression
# ----------------------------

data['Pass_Fail'] = (data['G3'] >= 10).astype(int)

y_log = data['Pass_Fail']

X_train, X_test, y_train, y_test = train_test_split(
    X, y_log, test_size=0.2, random_state=42
)

log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train, y_train)

log_pred = log_model.predict(X_test)

print("\nLOGISTIC REGRESSION")
print("Accuracy:", round(accuracy_score(y_test, log_pred), 2))

# ----------------------------
# Sample Prediction
# ----------------------------

student = [[4, 1, 3]]

grade = linear_model.predict(student)

result = log_model.predict(student)

print("\nSample Student Prediction")
print("Predicted Grade:", round(grade[0], 2))

if result[0] == 1:
    print("Result: PASS")
else:
    print("Result: FAIL")