# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oSKYnC2oIZljJDWdoVw48okKun9xDuCA
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

uploaded = files.upload()

data = pd.read_csv("Student_Data.csv")

print("Dataset Loaded Successfully")
print(data.head())

# Pass/Fail Target

data["Pass_Fail"] = (data["G3"] >= 10).astype(int)

X = data[['studytime','failures','absences']]

y = data['Pass_Fail']

print("Features Shape:", X.shape)

tree = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

tree.fit(X,y)

plt.figure(figsize=(12,6))

plot_tree(
    tree,
    feature_names=X.columns,
    class_names=['Fail','Pass'],
    filled=True
)

plt.title("Decision Tree")
plt.show()

print("Decision Tree Completed")

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X,y)

importance = rf.feature_importances_

plt.figure(figsize=(6,4))

plt.bar(
    X.columns,
    importance
)

plt.title("Feature Importance")
plt.ylabel("Importance Score")

plt.show()

print("Random Forest Completed")

Q = np.zeros((5,5))

rewards = []

for i in range(20):

    reward = np.random.randint(1,10)

    Q[1,1] += 0.1*(reward-Q[1,1])

    rewards.append(Q[1,1])

plt.figure(figsize=(7,4))

plt.plot(
    rewards,
    marker='o'
)

plt.title("Q Learning Reward Growth")
plt.xlabel("Episode")
plt.ylabel("Reward")

plt.grid()

plt.show()

svm = SVC()

svm.fit(X,y)

prediction = svm.predict([[4,1,3]])

plt.figure(figsize=(7,5))

plt.scatter(
    X['studytime'],
    X['failures'],
    c=y
)

plt.title("SVM Classification")
plt.xlabel("Study Time")
plt.ylabel("Failures")

plt.show()

print("Prediction:", prediction[0])

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X)

plt.figure(figsize=(7,5))

plt.scatter(
    X_pca[:,0],
    X_pca[:,1],
    c=y
)

plt.title("PCA Visualization")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")

plt.show()

print(
    "Variance Explained:",
    pca.explained_variance_ratio_
)

x_lstm = X.values

y_lstm = data["G3"].values

x_lstm = x_lstm.reshape(
    (
        x_lstm.shape[0],
        1,
        x_lstm.shape[1]
    )
)

model = Sequential()

model.add(
    LSTM(
        16,
        input_shape=(1,3)
    )
)

model.add(Dense(1))

model.compile(
    optimizer='adam',
    loss='mse'
)

history = model.fit(
    x_lstm,
    y_lstm,
    epochs=20,
    verbose=0
)

plt.figure(figsize=(7,4))

plt.plot(
    history.history['loss']
)

plt.title("LSTM Training Loss")

plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.grid()

plt.show()

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

X_dqn=np.array([
    [1,0],
    [2,1],
    [3,1],
    [4,0],
    [5,1]
])

y_dqn=np.array([
    5,
    7,
    9,
    11,
    8
])

dqn=Sequential()

dqn.add(
    Dense(
        16,
        activation='relu',
        input_shape=(2,)
    )
)

dqn.add(Dense(1))

dqn.compile(
    optimizer='adam',
    loss='mse'
)

history=dqn.fit(
    X_dqn,
    y_dqn,
    epochs=50,
    verbose=0
)

plt.figure(figsize=(7,4))

plt.plot(history.history['loss'])

plt.title("DQN Training Loss")

plt.show()

sample=np.array([[3,1]])

prediction=dqn.predict(
    sample,
    verbose=0
)

print(
    "Predicted Reward:",
    round(float(prediction[0][0]),2)
)