# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ps31y3T5HV0AUi-LGiKD7eq7nc77CXjm
"""

!pip install scikit-learn pandas

import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("chatbot_edu_dataset.csv")

print(df.head())

print("Dataset Shape:", df.shape)

df = df.dropna()

df["input"] = df["input"].astype(str)

df["target"] = df["target"].astype(str)

print(df.shape)

questions = df["input"]

answers = df["target"]

print("Questions Loaded:", len(questions))

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(questions)

print("Knowledge Base Ready")

def chatbot(query):

    query_vector = vectorizer.transform([query])

    similarity = cosine_similarity(
        query_vector,
        X
    )

    index = similarity.argmax()

    confidence = similarity[0][index]

    return answers.iloc[index], confidence

print("="*60)
print("EDUCATIONAL AI CHATBOT")
print("Created by HITHAISH")
print("Type 'exit' to stop")
print("="*60)

while True:

    user = input("\nYou : ").lower()

    # Exit
    if user == "exit":
        print("Bot : Goodbye! Have a great day.")
        break

    # Greetings
    elif user in ["hi","hello","hey"]:
        print("Bot : Hello! How can I help you today?")

    elif user == "good morning":
        print("Bot : Good Morning! Hope you have a productive day.")

    elif user == "good afternoon":
        print("Bot : Good Afternoon! How may I assist you?")

    elif user == "good evening":
        print("Bot : Good Evening! Hope your day is going well.")

    elif user == "good night":
        print("Bot : Good Night! Sweet dreams and take care.")

    elif user == "how are you":
        print("Bot : I am doing great. Thanks for asking!")

    elif user == "what's up" or user == "whats up":
        print("Bot : Just helping users learn and explore AI!")

    elif user == "thank you":
        print("Bot : You're welcome!")

    elif user == "bye":
        print("Bot : Goodbye! See you again soon.")
        break

    # Personal Questions

    elif "who created you" in user:
        print("Bot : I was developed by HITHAISH as an Educational AI Chatbot project.")

    elif "who made you" in user:
        print("Bot : I was created by HITHAISH for Assignment 4.")

    elif "your name" in user:
        print("Bot : My name is Educational AI ChatBot.")

    elif "who are you" in user:
        print("Bot : I am an Educational Knowledge-Based Chatbot.")

    # Dataset Questions

    else:

        answer, score = chatbot(user)

        print(
            "\nConfidence Score:",
            round(float(score),3)
        )

        print("Bot :", answer)